version: "3.2"

services:
  vox-homepage:
    image: 'yexingmiren/vox-homepage:latest'
    container_name: vox-homepage
    volumes:
    - ./conf:/app/conf
    - ./uploads:/app/uploads
    - ./database:/app/database
    ports:
    - 3002:3002
    restart: always